### ISSUE TITLE
Regarding OurOwnNieClientImpl 

### ISSUE THREAD

**Issue by keyhan** [navikt/eessi#1]
Hi there, I am part of the team in Swedish Pension Agency looking at Rina.

I was wondering about OurOwnNieClientImpl. Wouldn't it be better to implement it in such a way that is asks the National Application for configuration? In that way every time you update the national application the RINA would not need to be updated with what new case and document types are supported.

For high traffic too many rest requests would be done to NationalApplication, solution to that is to cache the answer for 1 hour for example.

**Comment by warild** [comment]
Hi - Thanks for Your comment. 
With the NIE-Client it should be possible to handle the document/case -events in any way one might like. It should as well be possible to do what you suggests.

The implementation in 'OurOwnNieClinetImpl' is just a simple demonstration giving us a starting point. 

It should also be noticed that this code is relatet to the PRR version of Rina (a "Post PRR" Version of Rina has later been released ).

**Comment by keyhan** [comment]
Thnx
